# Generated by Django 2.2.7 on 2019-11-11 06:59

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='json_data',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
