# Generated by Django 2.2.7 on 2019-11-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.CharField(default=None, max_length=32, unique=True),
        ),
    ]
