# Generated by Django 2.2.7 on 2019-11-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
    ]
